apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: test
            url: "{{ .Values.env.test.url }}"
  template:
    metadata:
      name: "tempo-{{ "{{" }}cluster{{ "}}" }}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1" 
    spec:
      project: tracing
      source:
        repoURL: "https://github.com/selcuksan/didak-installation-components.git"
        targetRevision: HEAD
        path: environments/{{ "{{" }}cluster{{ "}}" }}/tracing-stack/
      destination:
        server: "{{ "{{" }}url{{ "}}" }}"
        namespace: tracing
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

