apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-adapter
  namespace: argocd
spec:
  generators:
  - list:
        elements:
        - cluster: test
          url: '{{ .Values.env.test.url }}'
  template:
    metadata:
      name: 'prometheus-adapter-{{ "{{" }}cluster{{ "}}" }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
    spec:
      project: monitoring
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: prometheus-adapter
          targetRevision: 4.14.0
          helm:
            valueFiles:
              - $values/environments/{{ "{{" }}cluster{{ "}}" }}/monitoring-stack/prometheus-adapter-values.yaml
        - repoURL: "https://github.com/selcuksan/didak-installation-components.git"
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{ "{{" }}url{{ "}}" }}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
